# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-global-accelerator-endpoint-group
  description: This component is responsible for provisioning a Global Accelerator Endpoint Group
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component






